#                                                ## Numpy Library Tutorial

# How to import NumPy

In [1]:
import numpy as np

# Creating Arrays - One/Two/Multi Dimensional Arrays

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

In [267]:
a = np.array([1, 2, 3], dtype='int16')

In [268]:
type(a)

numpy.ndarray

In [269]:
b=np.array([[1, 2, 3], [4, 5, 6]])

In [270]:
print(b)

[[1 2 3]
 [4 5 6]]


In [271]:
c=np.array([[[1,2, 3, 4]], [[4, 5, 6, 7]], [[7, 8, 9,10]]])

In [272]:
print(c)

[[[ 1  2  3  4]]

 [[ 4  5  6  7]]

 [[ 7  8  9 10]]]


An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

[[0., 0., 0.],
 [1., 1., 1.]]
Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3.

Just like in other Python container objects, the contents of an array can be accessed and modified by indexing or slicing the array. Unlike the typical container objects, different arrays can share the same data, so changes made on one array might be visible in another.

# Axis

For axis=0, this means that we apply a function along each “column”, or all values that occur vertically.

For axis=1, this means that we apply a function along each “row”, or all values horizontally.

# Get Dim, Shape, Type, Size, Total Size, Number of Elements

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [273]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [274]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3, 1, 4)


In [34]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int16
int32
int32


In [35]:
print(a.size)
print(b.size)
print(c.size)

3
6
12


In [36]:
print(a.nbytes)
print(b.nbytes)
print(c.nbytes)

6
24
48


In [275]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

2
4
4


In [281]:
#Reshape

a=np.arange(0,8)
print(a)
print(np.reshape(a, newshape=(4, 2)))
print(np.reshape(a, newshape=(2, 4)))

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]


# Accessing/Changing specific elements, rows, columns, etc

In [39]:
a=np.array([1, 2, 3])
print(a)

[1 2 3]


In [83]:
# Get a specific element [r, c]
print(a[1])
print(a[0:])

2
[1 2 3]


In [47]:
b=np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [88]:
print(b[1, 1])
print(b[0, 0])
print(b[0, 2])
print(b[0, :-1])
print(b[-1:])

5
1
3
[1 2]
[[4 5 6]]


In [69]:
c=np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [8, 9, 10, 11]]])
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 8  9 10 11]]]


In [72]:
print(c[0, 0, 0])
print(c[0, 1, 1])
print(c[0, 2, 3])

1
6
11


In [77]:
d=np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [8, 9, 10, 11]], 
            [[11, 21, 31, 41], [51, 61, 71, 81], [81, 91, 101, 111]]]
          )
print(d)

[[[  1   2   3   4]
  [  5   6   7   8]
  [  8   9  10  11]]

 [[ 11  21  31  41]
  [ 51  61  71  81]
  [ 81  91 101 111]]]


In [80]:
print(d[0, 0, 0])
print(d[1, 1, 1])
print(d[1, 2, 3])

1
61
111


# Initializing Different Types of Arrays

In [107]:
# All 0s matrix

a=np.zeros(2)
b=np.zeros((2, 3))
c=np.zeros((2, 3, 4))
d=np.zeros((2, 3, 4), dtype='int32')


In [105]:
print(a)


[0. 0.]


In [104]:
print(b)


[[0. 0. 0.]
 [0. 0. 0.]]


In [106]:
print(c)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [108]:
print(d)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [109]:
# All 1s matrix

a=np.ones(2)
b=np.ones((2, 3))
c=np.ones((2, 3, 4))
d=np.ones((2, 3, 4), dtype='int32')

In [112]:
print(a)
print(b)
print(c)
print(d)

[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [113]:
a=np.empty(2)
b=np.empty((2, 3, 4))

In [114]:
print(a)

[1. 1.]


In [116]:
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [121]:
# Any other number
np.full((2, 2, 4), 18)

array([[[18, 18, 18, 18],
        [18, 18, 18, 18]],

       [[18, 18, 18, 18],
        [18, 18, 18, 18]]])

In [118]:
# Any other number (full_like)
np.full_like(b, 4)

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [124]:
# Random decimal numbers - Shows randow numbers between 0 and 1
np.random.rand(3,2)

array([[0.05271935, 0.11000433],
       [0.05628501, 0.17200622],
       [0.25215586, 0.20997492]])

In [127]:
# Random Integer values
np.random.randint(0,10, size=(3,2))

array([[3, 7],
       [2, 0],
       [5, 8]])

In [128]:
# The identity matrix
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [133]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r2 = np.repeat(arr,3, axis=1)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [136]:
#You can create an array with a range of elements:

np.arange(9)


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [138]:
#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval: num= number of samples

np.linspace(1, 9, num=3)

array([1., 5., 9.])

In [144]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [146]:
np.linspace(0, 10, 5, axis=0)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Be careful when copying arrays!!!

In [147]:
a = np.array([1,2,3])
b = a.copy()
print(b)
b[0] = 100

print(a)
print(b)

[1 2 3]
[1 2 3]
[100   2   3]


# Adding, removing, and sorting elements

In [155]:
arr=np.array([2, 5, 3, 6, 4, 7, 1, 9, 8])

In [156]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
#Concantenation

a=np.array([1, 2, 3])
b=np.array([4, 5, 6, 7])

In [176]:
d=np.concatenate((a, b))

In [168]:
c=np.array(['hello'])

In [169]:
c

array(['hello'], dtype='<U5')

In [173]:
print(np.concatenate((a, b, c)))

['1' '2' '3' '4' '5' '6' '7' 'hello']


In [188]:
#Delete elements np.delete(input array, obj, axis=none)

print(d)
print(np.delete(d, 2))
print(np.delete(d, [4, 5]))
print(np.delete(d, np.s_[1:]))

[1 2 3 4 5 6 7]
[1 2 4 5 6 7]
[1 2 3 4 7]
[1]


In [193]:
#insert new elements in an array - np.insert(arr, obj- index before, values, axis=none)

a=np.array([1, 2, 3])
np.insert(a, 1, 4)


array([1, 4, 2, 3])

In [198]:
b=np.array([[1, 2, 3], [4, 5, 6]])

print(np.insert(b, 1, 7))
print(np.insert(b, 1, 7, axis=0))
print(np.insert(b, 1, 7, axis=1))

[1 7 2 3 4 5 6]
[[1 2 3]
 [7 7 7]
 [4 5 6]]
[[1 7 2 3]
 [4 7 5 6]]


In [199]:
#append elements to the end of the array - numpy.append(arr, values, axis=none)


a=np.array([1, 2, 3])
np.append(a, 4)


array([1, 2, 3, 4])

In [215]:
b=np.array([[1, 2, 3], [4, 5, 6]])

print(np.append(b, 7))
print(np.append(b, [[7, 8, 9]], axis=0))
print(np.append([[1, 2, 3]], [[10, 11, 12]], axis=0))
print(np.append([[1, 2, 3]], [[10, 11, 12]], axis=1))


[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 11 12]]
[[ 1  2  3 10 11 12]]


In [228]:
#Transpose

print(b)
print(np.transpose(b))


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [230]:
#Repeat- np.repeat(a, repeats, axis=none)

a=np.array(4)
np.repeat(a, 4)

array([4, 4, 4, 4])

In [256]:
b=np.array([[1, 2, 3], [4, 5, 6]])
print(np.repeat(b, 2, axis=1))
print(np.repeat(b, 2, axis=0))
print(np.repeat(c, 2, axis=2))

[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]
[[[ 1  1  2  2  3  3  4  4]
  [ 4  4  5  5  6  6  7  7]
  [ 7  7  8  8  9  9 10 10]]]


In [255]:
c=np.array([[[1,2, 3, 4], [4, 5, 6, 7], [7, 8, 9,10]]])

In [257]:
#unique

a=np.array([1, 1, 2, 2, 3, 3])
np.unique(a)

array([1, 2, 3])

In [262]:
b=np.array([[1, 2, 3, 1], [1, 2, 3, 1]])
print(np.unique(b, axis=1))
print(np.unique(b, axis=0))

[[1 2 3]
 [1 2 3]]
[[1 2 3 1]]


In [285]:
#Add a new axis to an array

a=np.array([1, 2, 3, 4, 5])
print(a)
print(a.shape)
a1=a[np.newaxis, :]
a2=a[:, np.newaxis]
a3=np.expand_dims(a, axis=1)
a4=np.expand_dims(a, axis=0)
print(a1)
print(a2)
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
(1, 5)
(5, 1)
(5, 1)
(1, 5)


# Mathematics

In [293]:
a = np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [294]:
a+2

array([12, 22, 32, 42])

In [295]:
a-5

array([ 5, 15, 25, 35])

In [296]:
a*4

array([ 40,  80, 120, 160])

In [297]:
a/2

array([ 5., 10., 15., 20.])

In [298]:
a%3

array([1, 2, 0, 1], dtype=int32)

In [299]:
a//3

array([ 3,  6, 10, 13], dtype=int32)

In [300]:
a**2

array([ 100,  400,  900, 1600], dtype=int32)

In [302]:
b=np.array([1, 2, 3, 4])
a+b

array([11, 22, 33, 44])

In [303]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806])

# How to create an array from existing data

In [312]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [313]:
a1=a[5:]

In [314]:
a1

array([ 6,  7,  8,  9, 10])

In [317]:
#vstack and hstack

a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])

In [319]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [320]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [330]:
#split

a=np.arange(1, 25).reshape(2, 12)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [335]:
np.hsplit(a, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [336]:
#To split after third and fourth column

np.hsplit(a, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [348]:
a=np.arange(1, 13).reshape(4, 3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [352]:
np.vsplit(a, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

# Statistics

In [353]:
a=np.arange(1, 13).reshape(4, 3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [354]:
print(a.max())
print(a.min())
print(a.sum())

12
1
78


In [356]:
print(a.max(axis=0))
print(a.min(axis=0))
print(a.sum(axis=0))
print(a.max(axis=1))
print(a.min(axis=1))
print(a.sum(axis=1))
print(a.mean(axis=0))
print(a.std(axis=0))
print(a.mean(axis=1))
print(a.std(axis=1))

[10 11 12]
[1 2 3]
[22 26 30]
[ 3  6  9 12]
[ 1  4  7 10]
[ 6 15 24 33]
[5.5 6.5 7.5]
[3.35410197 3.35410197 3.35410197]
[ 2.  5.  8. 11.]
[0.81649658 0.81649658 0.81649658 0.81649658]


In [357]:
#flip

a=np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [358]:
np.flip(a)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [361]:
a1=a.reshape(2, 5)
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [362]:
np.flip(a1)

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [363]:
print(np.flip(a1, axis=0))
print(np.flip(a1, axis=1))

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]]


# Reshaping and Flattening multidimensional arrays

There are two popular ways to flatten an array: .flatten() and .ravel(). The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.

In [367]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [368]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [370]:
a1=x.flatten()
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [371]:
a1[0]=99

In [372]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [373]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [374]:
a2=x.ravel()
a2[0]=98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [375]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


# How to save and load NumPy objects

In [381]:
#for saving array objects - use save, load and for saving txt/csv - use savetxt, loadtxt


a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [377]:
np.save('filename', a)

In [378]:
np.load('filename.npy')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [379]:
np.savetxt('new_file.csv', a)

In [380]:
np.loadtxt('new_File.csv')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [382]:
np.savetxt('new_file.txt', a)

In [383]:
np.loadtxt('new_File.txt')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [387]:
#Another way of importing text/csv

a=np.genfromtxt('new_file.txt', delimiter=',')
a=a.astype('int32')
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])